# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Accessed via {{ site.title }}, {{ site.email }}, and so on.

title: alex bumbu | Front-End Web Engineer
email: bumbu@github.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Alex Bumbu. Here you can find the blog,
  development articles, experiments and learning.
baseurl: ""
url: "https://bumbu.me"
twitter_username: bumbualex
github_username:  bumbu
google_analytics: UA-34516109-2
assets_path: "https://bumbu.me/assets/images/"
assets_cache_buster: "_=1"

# Content settings
sidebar:
  categories:
    home:
      id: home
      path: ''
      name: Home
      icon: icons/bumbu.svg
    blog:
      id: blog
      path: blog
      name: Blog
      icon: icons/daily-newspaper.svg
    development:
      id: development
      path: development
      name: Development
      icon: icons/small-light-bulb.svg
    experiments:
      id: experiments
      path: experiments
      name: Experiments
      icon: icons/chemistry.svg
    learning:
      id: learning
      path: learning
      name: Learning
      icon: icons/graduation-cap.svg
    about:
      id: about
      path: about
      name: About
      icon: icons/user-avatar.svg
    search:
      id: search
      path: search
      name: Search
      icon: icons/zoom-tool.svg

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

theme: minima
gems:
  - jekyll-feed
permalink: /:slug/
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - node_modules/
  - gulpfile.js
  - package.json
  - _source/
  - jsconfig.json
  - TODO.md
  - .editorconfig
  - .gitignore

prose:
  rooturl: '_posts'
  siteurl: 'https://bumbu.me'
  media: 'assets/images'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'category'
        field:
          element: 'select'
          label: 'Add Categories'
          placeholder: 'Choose Tags'
          options:
            - name: 'Blog'
              value: 'blog'
            - name: 'Development'
              value: 'development'
            - name: 'Experiments'
              value: 'experiments'
            - name: 'Learning'
              value: 'learning'
            - name: 'About'
              value: 'about'
            - name: 'Projects'
              value: 'projects'
